[project]
name = "django-practice"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "shailesh", email = "prajapatishailesh4941@gmail.com" }
]
requires-python = ">=3.14.7"
dependencies = [
    "django>=6.1.1",
]

[project.scripts]
django-practice = "django_practice:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"
